name: Check code format

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check_python:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: psf/black@stable
      with:
        options: "--check --diff --color"
        src: "."
        jupyter: true

  check_cpp:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: DoozyX/clang-format-lint-action@v0.20
      with:
        source: './src'
        clangFormatVersion: 20
        style: file

  check_docs_format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: pip install black[jupyter] jupytext
    - run: make check-format-doc
